name: Build GridDB server and execute java sample

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: 22.04
      GRIDDB_NOTIFICATION_ADDRESS: "239.0.0.1"
      GRIDDB_NOTIFICATION_PORT: "31999"
      GRIDDB_CLUSTER_NAME: "griddbDocker"
      GRIDDB_USERNAME: "admin"
      GRIDDB_PASSWORD: "admin"
      DOCKER_CONTAINER_NAME_UBUNTU: "griddbUbuntuDocker"
    steps:
    - uses: actions/checkout@v1
    - name: Build, start server and run sample in ubuntu docker
      run: |
        ./.github/workflows/setup_ubuntu_docker.sh
